[package]
name = "corekit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Small Rust ergonomics library for backend projects."
repository = "https://github.com/alexeichhorn/rust-corekit"
readme = "../../README.md"

[dependencies]
corekit-macros.workspace = true

[dev-dependencies]
ui_test = "0.30.5"

[[test]]
name = "singleton_ui"
path = "tests/singleton_ui.rs"
harness = false
